---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-service
  labels:
    app: angular-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app-service
  template:
    metadata:
      labels:
        app: angular-app-service
    spec:
      containers:
      - name: angular-app-service-container
        image: 463470954735.dkr.ecr.us-east-1.amazonaws.com/powernest_ui:latest
        ports:
        - containerPort: 4000
...