---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
  labels:
    app: angular-app-service
spec:
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: angular-app-service
  type: LoadBalancer
...